### PR TITLE
Yaakov refactor initial

### PR DESCRIPTION
**Pull request by ybressler**
Finished refactoring the code. Not to be petty – but the code at hand is in very poor state. Not much of it is usable. I’m not sure if you’ll want to keep this repo as is and have me create a new one – or for me to keep working on this one.

### CODE REVIEW

**Comment by ybressler** [comment]
Let's merge this as is --> then I'll create a new branch for the current data science work I'm doing.

**Comment by rashnil-git** [comment]
Lets use this repo for our experimentation and other ML stuffs notebook. create a folder in the root, `v2` and we will put our code there. Instead of Experimental, I would suggest rename it to archive and put all old stuff there including data?

**Comment by ybressler** [comment]
Got it. Will do just that @rashnil-git – give me a moment.

**Comment by rashnil-git** [comment]
I also renamed the repo .

**Comment by ybressler** [comment]
Check the outline, let me know if it's proper. If yes, I'll add my code to `v2`.

**Review by rashnil-git — APPROVED** [review]
Looks Good.

**Comment by rashnil-git** [comment]
Lets merge this and then you can raise a PR for your stuff separately?

**Pull request merged**
